on: push

permissions: write-all
jobs: 
  run_deployment:
    runs-on: ubuntu-latest
    #if: contains( ${{ github.event.head_commit.message }}, "deploy")
    name: Run deployment codepipeline 
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Setup python
       uses: actions/setup-python@v2
       with: 
          python-version: 3.8  
     - name: Install python Packages
       run: |
          python -m pip install --upgrade pip
          pip install boto3
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::336607023349:role/oidc-Role-14985HCQ88QRR
          role-session-name: TempSession
     - name: show the commit message and branch
       run: |
        echo ${{ github.event.head_commit.message }}
        echo ${{ github.ref_name }}
     - name: run pipeline
       if: startsWith( ${{ github.event.head_commit.message }}, "deploy" )
       run: python test.py -c "${{ github.event.head_commit.message }}" -b "${{ github.ref_name }}"
