on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: notify CS
        id: slack-cs
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          payload: |
            {
              "emoji": ":redsiren:",
              "status": "FAILED",
              "environment": "${{ github.event.inputs.environment }}",
              "repository": "${{ github.repository }}",
              "ref_name": "${{ github.ref_name }}",
              "actor": "${{ github.actor }}",
              "runlink": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }

