on: push

permissions:
  contents: write
  actions: write
  pull-requests: write
jobs:      
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: send dispatch to deploy workflow
        id: dispatch_deploy_event
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST \
              -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/linganikhilkumar/slack-notification-repo/actions/workflows/test.yml/dispatches \
              -d '{ "ref": "main", "inputs": { "environment": "dev", "version": "latest" }  }'

      - name: notify CS
        id: slack-cs
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          payload: |
            {
              "text":"hello ${{ github.actor }} <@nikhilkumar435@gmail.com> <@U03TFF058KY>",
              "username": "nikhilkumar435@gmail.com"
            }
                  

