name: CheckPendingWorkflows
on:
  schedule:
    - cron: "*/5 5 * * *"
  workflow_dispatch:
    inputs:
      environment:
        default: 'dev'
      version:
        default: 'latest'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:   
    - name: Get previous build status
      shell: bash
      id: last_status
      run: |
        ids=$(curl --silent --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                                    --header 'content-type: application/json' \
        "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs?per_page=5&status=waiting" \
        | jq -r .workflow_runs[].id )
        echo "::set-output name=id::$id"
        echo "Status of the previous build: $last_status"
