
on: 
  workflow_dispatch:
    inputs:
      environment:
        default: 'dev'
      version:
        default: 'latest'
jobs:      
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: notify CS
        id: slack-cs
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          payload: |
            {
              "text":"hello ${{ github.actor }} <@nikhilkumar435@gmail.com> <@U03TFF058KY>",
              "username": "nikhilkumar435@gmail.com"
            }
